name: lexicor
description: >-
  An optimized, strictly typed, offline interface for the Open English WordNet database.
version: 0.1.2

repository: https://github.com/puntbyte/lexicor
homepage: https://github.com/puntbyte/lexicor
issue_tracker: https://github.com/puntbyte/lexicor/issues
topics:
  - wordnet
  - dictionary
  - nlp
  - semantics
  - thesaurus

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.16.0
  path: ^1.9.1
  sqlite3: ^2.8.0

dev_dependencies:
  melos: ^7.3.0
  test: ^1.26.0
  very_good_analysis: ^10.0.0

melos:
  useRootAsPackage: true

  scripts:
    build:
      description: Build database
      run: dart run tool/build_database.dart tool/db/oewn.sqlite
